name: play
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audio_session: ^0.1.18
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  hooks_riverpod: ^2.4.9
  http: ^1.1.2
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
